name: dart_midi
description: A pure Dart MIDI parser and writer implementation. This package is platform agnostic and works on every dart platform.
version: 1.0.2
homepage: https://github.com/feelfreelinux/midi

environment:
  sdk: ^3.3.0

dev_dependencies:
  test: ^1.6.4